package com.example.approomiematchu.ui.profileconfig.presentation

data class PerfilState(
    val userId: Long = 0L,
    val tipoPerfil: TipoPerfil = TipoPerfil.NONE,
    val fotoPerfilLocalUri: String? = null, // URI local temporal
    val fotoPerfilUrl: String? = null,
    val fechaNacimiento: String = "",
    val genero: String? = null,
    val telefono: String? = null,
    val idioma: String? = null,
    val habitos: String = "",
    val mascota: Boolean? = null,
    val fuma: Boolean? = null,
    val alergico: Boolean? = null,
    val detalleAlergia: String? = null,
    val descripcionLibre: String? = null,
    val presupuesto: Double? = null,
    val barrio: String? = null,
    val tipoHabitacion: String? = null,
    val tiempoEstancia: String? = null,
    val personasConvivencia: String? = null,
    val fechaMudanza: String? = null,
    val serviciosDeseados: String? = null,
    val arriendo: Double? = null,
    val cantidadHabitaciones: Int? = null,
    val maxRoomies: Int? = null,
    val reglasConvivencia: String? = null,
    val serviciosIncluidos: String? = null,
    val fotosResidencia: List<String> = emptyList(),
    val pasoActual: Int = 1,
    val isLoading: Boolean = false,
    val error: String? = null,
    val success: Boolean = false
)